### ISSUE TITLE
Hast du das mit dem Chefkoch-Team abgesprochen?

### ISSUE THREAD

**Issue by madebyfabian** [florianschmidt1994/chefkoch-api#1]
Hi,

hab den Forenbeitrag gelesen und würde die API ebenfalls gerne nutzen. Würde den wrapper allerdings in Node.js umschreiben. Eigentlich hat das Chefkoch-Team ja ausdrücklich gesagt, dass die API nicht öffentlich ist und deshalb nicht genutzt werden darf. Wollte nur Fragen ob und wenn wie sie es dir erlaubt haben. Will ja kein Risiko eingehen 😄

LG Fabian

**Comment by Disane87** [comment]
Was sollte denn das Risiko sein? Ob du jetzt automatisiert zugreifst oder über einen Browser, das ist von den Requests her das Selbe. Wenn die nicht wollen, dass man auf die API zugreifen darf, dann sollen die die auch mit CORS gefälligst komplett dicht machen und sich hinterher nicht beschweren 😬

**Comment by florianschmidt1994** [comment]
Hi @madebyfabian. Sorry für die verzögerte Antwort, ich hatte das Projekt nicht im Blick. Ich habe das ganze nicht mit dem Team abgesprochen und muss an dieser Stelle darauf hinweisen, dass jeder das ganze selbst entscheiden muss, wie und ob er das ganze verwenden möchte

**Comment by elia-driesner** [comment]
ist es irgendwie möglich das rezept des tages von chefkoch anzufragen?

**Comment by Disane87** [comment]
> ist es irgendwie möglich das rezept des tages von chefkoch anzufragen?

Mach doch dafür ein neuen Issue auf. Das sind doch sonst vermischte Themen die nicht zusammengehören.
