### ISSUE TITLE
Überhaupt noch aktuell?

### ISSUE THREAD

**Issue by Disane87** [florianschmidt1994/chefkoch-api#2]
Ich habe mir dein Script geladen musste aber feststellen, dass es scheinbar nicht mehr funktioniert. Beim Auth lande ich immer auf der "Einloggen"-Seite. Das selbe Verhalten konnte ich auch mit einer NodeJS-Anwendung nachstellen.

Witziger weise klappt es im Postman ohne Probleme und dort bekomme ich eine saubere Response mit dem Body `Schön, dass du wieder da bist`.

Funktioniert das Script überhaupt noch oder hat Chefkoch da mittlerweile einen Riegel vorgeschoben?

**Comment by florianschmidt1994** [comment]
Hallo @Disane87, tut mir leid dass es fast ein Jahr gedauert hat, bis du eine Antwort von mir bekommst. Ich habe dieses Projekt nur einmal verwendet und seither nicht mehr maintained, also ist es gut möglich, dass das ganze nicht mehr funktioniert.
Ich werde dem Repo eine Warnung in die Readme packen, damit das in Zukunft jedem gleich klar ist :)
